import Head from 'next/head'
import styles from '../styles/Home.module.css'
import NavBar from '../components/navBar.jsx'
import Footer from '../components/footer'
import { Box, Button, Container, Modal, Snackbar, Typography } from '@mui/material'
import Layout from '../components/layout'
export default function Home() {


  return (
    <>
      <Head>
        <title>Habesha Donate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
      <Box mt={0}
      sx={{
        height:'100vh',
        backgroundImage:`url(/hero.jpeg)`,
        backgroundPosition:'center',
        backgroundSize:'cover',
        backgroundRepeat:'no-repeat',
        display:'flex',
        backgroundAttachment:'fixed',
        justifyContent:'center',
        alignItems:'center'
      }}
      >

      <Box
      sx = {{
        display:'flex',
        flexDirection:"column",
        alignItems:'center',
        padding:1
      }}
      >
        <Typography align='center' variant='h3' color='white' >
          Come And Lets Save Lives With Just Our Blood
        </Typography>
        <Button sx={{margin:4}} variant= {'contained'}>
          Donate Now
        </Button>
      </Box>
      </Box>
      </Layout>
    </>
  )
}