import Head from 'next/head'
import styles from '../styles/Home.module.css'
import image from '../public/lo.png'
import NavBar from '../components/navBar.jsx'
import Image from 'next/image'
export default function Home() {


  return (
    <div className={styles.container}>
      <Head>
        <title>Habesha Donate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar></NavBar>
      <Image src = {image}></Image>
    </div>
  )
}
